version: "3.8"
services:
  frontend:
    build: ./frontend/spring-petclinic-angular
    image: anassumrani/frontend:latest
    ports:
    - target: 4200
      published: 4200
      protocol: tcp
    depends_on: 
    - "backend"
  backend:
    image: anassumrani/backend:latest
    ports:
    - target: 9966
      published: 9966
      protocol: tcp
  nginx:
    build: ./nginx
    image: anassumrani/nginx:latest
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - "frontend"
