---
# tasks file for update-apt

- name: "update apt packages"
  apt:
    upgrade: yes
    update_cache: yes
    
- name: "install git and python3 and python pip"
  apt:
    name:
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: "install unzip, wget and maven"
  apt:
    pkg: 
    - unzip
    - wget
    - maven